# fly.toml file generated for floral-sunset-5380 on 2023-02-20T22:16:34+01:00

app = "holy-darkness-161"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
auto_rollback = true

[build]
dockerfile = "Dockerfile"

[[services]]
internal_port = 8000
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = "15s"
grace_period = "5s"
method = "get"
path = "/health_check"
protocol = "http"
restart_limit = 0
timeout = "2s"
tls_skip_verify = true
